#!/usr/bin/env python3
"""Build the Session 2 challenge notebooks.

Two notebooks, deliberately different in kind:

Session 2 — the shape of the task:

* `aie-s2-bike-demand.ipynb`  — **worked**. Runs end to end and produces a
  submission that scores the challenge's declared baseline. This is the one a
  student reads to learn the shape of the task.
* `aie-s2-bank-marketing.ipynb` — **guided**. The same steps in English, with
  empty cells. No code: the student writes it, having just read the other one.

Session 3 — why the training score is not the score:

* `aie-s3-diabetes-progression.ipynb` — **worked**. Fits a linear model and a
  heavy random forest, shows the forest winning on training and losing on
  held-out data, and lets cross-validation call it correctly in advance.
  Submits both so the leaderboard settles it.
* `aie-s3-credit-risk.ipynb` — **guided**. Same protocol, no code.

Both are written to `website/public/modules/python-ai-engineering/challenges/`,
which is what makes the Colab link work — Colab reads the file from GitHub at
`colab.research.google.com/github/<owner>/<repo>/blob/<branch>/<path>`.

    python courseware/tools/build_notebooks.py

Regenerate after editing this file; the .ipynb files are committed so the Colab
links resolve, but this script is the source.
"""
from __future__ import annotations

import itertools
import json
import pathlib

REPO = pathlib.Path(__file__).resolve().parents[2]
OUT = REPO / "website" / "public" / "modules" / "python-ai-engineering" / "challenges"

GITHUB = "racousin/data_science_practice"
BRANCH = "main"

BIKE_ID = 183
BANK_ID = 184
DIABETES_ID = 185
CREDIT_ID = 186


def colab_url(name: str) -> str:
    rel = f"website/public/modules/python-ai-engineering/challenges/{name}"
    return f"https://colab.research.google.com/github/{GITHUB}/blob/{BRANCH}/{rel}"


_COUNTER = itertools.count()


def _cell_id() -> str:
    """nbformat >= 4.5 requires a per-cell id, and warns loudly without one.
    Derived from a counter so regenerating is byte-identical (the sync test
    depends on that)."""
    return f"c{next(_COUNTER):03d}"


def md(*lines: str) -> dict:
    return {"cell_type": "markdown", "id": _cell_id(), "metadata": {},
            "source": _src(lines)}


def code(*lines: str) -> dict:
    return {"cell_type": "code", "id": _cell_id(), "execution_count": None,
            "metadata": {}, "outputs": [], "source": _src(lines)}


def _src(lines) -> list[str]:
    text = "\n".join(lines)
    out = text.splitlines(keepends=True)
    return out or [""]


def notebook(cells: list[dict]) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python",
                           "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
            "colab": {"provenance": []},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


# --------------------------------------------------------------------------- #
# 0. pandas & seaborn — the pre-flight notebook
# --------------------------------------------------------------------------- #
def build_preflight() -> dict:
    """Companion to the `Reference — pandas & seaborn` lesson in Session 1.

    Needs no API key and no ML-Arena account: it runs on seaborn's bundled
    penguins frame, which is also the dataset Session 2's "The Data" lesson is
    built on, so the student meets the same table twice.
    """
    name = "aie-s0-pandas-seaborn.ipynb"
    return notebook([
        md(
            "# AIE — pandas & seaborn, before Session 2",
            "",
            f"[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]({colab_url(name)})",
            "",
            "Every session from 2 onward reads a CSV, reshapes it, and plots it.",
            "This notebook is the subset of `pandas` and `seaborn` those sessions",
            "actually use — nothing more — with the code in front of you rather",
            "than described.",
            "",
            "**Run it before Session 2.** It needs no API key and no account: the",
            "data ships with seaborn. It is the same penguins table Session 2's",
            "*The Data* lesson is built on, so you meet it twice.",
            "",
            "The written version is the *Reference — pandas & seaborn* lesson in",
            "Session 1. Read either; do this one.",
        ),
        md("---", "", "## 1. The DataFrame",
           "",
           "A `DataFrame` is a dictionary of **typed columns** sharing one index.",
           "Both halves matter: each column has a single dtype (not each cell),",
           "and columns align by index label rather than by position."),
        code(
            "import pandas as pd",
            "import seaborn as sns",
            "import matplotlib.pyplot as plt",
            "",
            'df = sns.load_dataset("penguins")',
            "df.head()",
        ),
        md("### The four lines to run on any new table",
           "",
           "In this order, every time, before modelling anything."),
        code(
            'print("shape:", df.shape)          # (n, p)',
            'print()',
            "print(df.dtypes)",
        ),
        md("`dtypes` is the line people skip and the one that bites. pandas infers",
           "types when it reads: one stray `\"N/A\"` in a numeric column and the",
           "whole column comes back as text, after which arithmetic on it fails —",
           "or silently concatenates.",
           "",
           "Here four columns are `float64` and three are text."),
        code(
            "df.isna().sum()",
        ),
        md("Missing values, per column. `isna()` returns a frame of booleans the",
           "same shape as `df`, so `.sum()` counts down each column."),
        code(
            "df.describe()",
        ),
        md("**Look at `count`.** It says 342, and the frame has 344 rows —",
           "`describe` drops missing values without saying so, and that gap is",
           "your first evidence they exist."),
        md("---", "", "## 2. Selecting",
           "",
           "One bracket gives a **Series**, two give a **DataFrame**. Keep track",
           "of which you are holding."),
        code(
            'print(type(df["species"]))',
            'print(type(df[["species", "island"]]))',
        ),
        md("Rows come out with a boolean mask. Note `&`, not `and` — and the",
           "parentheses, which are required."),
        code(
            'heavy = df[df["body_mass_g"] > 5000]',
            'print(len(heavy), "penguins over 5kg")',
            "",
            'subset = df[(df["sex"] == "Male") & (df["island"] == "Dream")]',
            'print(len(subset), "male penguins on Dream")',
        ),
        md("`and` genuinely does not work there: `&` compares element by element",
           "over the whole column, while `and` tries to reduce it to one true or",
           "false and raises.",
           "",
           "Dropping is by keyword — and the keyword is load-bearing."),
        code(
            'X = df.drop(columns=["species"])   # NOT df.drop("species"), which drops a ROW',
            'print(list(X.columns))',
        ),
        md("Splitting numeric from categorical is a step every challenge notebook",
           "performs, because the two halves get different treatment."),
        code(
            'print("numeric    :", list(df.select_dtypes("number").columns))',
            'print("categorical:", list(df.select_dtypes(exclude="number").columns))',
        ),
        md("---", "", "## 3. Summarising — does this column carry signal?",
           "",
           "`groupby` answers that before any model does. Read it as **split →",
           "apply → combine**."),
        code(
            'df.groupby("species")["body_mass_g"].agg(["count", "mean", "std"])',
        ),
        md("The within-species spreads are far below the pooled one, so `species`",
           "explains a large share of the variance in mass. That is the statement",
           "\"this feature is informative\", made before fitting anything.",
           "",
           "### The rate trick",
           "",
           "For a **0/1 target the mean of the column is its rate**, which makes",
           "this the single most useful line in exploratory work on a classifier."),
        code(
            'penguins = df.assign(is_gentoo=(df["species"] == "Gentoo").astype(int))',
            'penguins.groupby("island")["is_gentoo"].agg(["count", "mean"])',
        ),
        md("`count` says which islands are common; `mean` says which are",
           "predictive. Different questions — and it is the second one you want.",
           "Gentoos are only ever found on Biscoe.",
           "",
           "`assign` above added a column and returned a new frame, leaving `df`",
           "untouched."),
        md("---", "", "## 4. seaborn",
           "",
           "Two facts explain most of the API.",
           "",
           "**Every plot takes tidy data**: hand it the whole frame and name the",
           "columns. It does the grouping, the aggregation and the legend.",
           "",
           "**`hue=` splits any plot by a third column.** It is the highest-value",
           "argument in the library."),
        code(
            'sns.set_theme(style="whitegrid")',
            "",
            "fig, axes = plt.subplots(1, 2, figsize=(11, 4))",
            'sns.histplot(data=df, x="body_mass_g", ax=axes[0])',
            'sns.histplot(data=df, x="body_mass_g", hue="species", ax=axes[1])',
            'axes[0].set_title("without hue")',
            'axes[1].set_title("with hue=\'species\'")',
            "plt.tight_layout()",
            "plt.show()",
        ),
        md("The same data. The right-hand panel shows the left-hand one is two",
           "populations, not a wide one.",
           "",
           "### Axes-level and figure-level",
           "",
           "The distinction behind most \"why is my figure blank\" questions:",
           "",
           "| | draws onto | takes `ax=` |",
           "|---|---|---|",
           "| **axes-level** — `histplot`, `barplot`, `boxplot`, `lineplot`, `regplot`, `heatmap`, `countplot` | a subplot you give it | yes |",
           "| **figure-level** — `pairplot`, `relplot`, `catplot`, `displot` | a whole figure it makes itself | **no** |",
           "",
           "So `pairplot` cannot go inside a grid you built. It *is* the grid."),
        md("### The plots this course uses",
           "",
           "Four axes-level plots, placed into one figure."),
        code(
            "fig, axes = plt.subplots(2, 2, figsize=(12, 8))",
            'sns.boxplot(data=df, x="species", y="body_mass_g", ax=axes[0, 0])',
            'axes[0, 0].set_title("boxplot — does y differ across levels?")',
            "",
            'sns.countplot(data=df, x="island", ax=axes[0, 1])',
            'axes[0, 1].set_title("countplot — how many rows per level?")',
            "",
            'sns.regplot(data=df, x="flipper_length_mm", y="body_mass_g",',
            '            scatter_kws=dict(alpha=0.4, s=12), ax=axes[1, 0])',
            'axes[1, 0].set_title("regplot — is the relationship linear?")',
            "",
            'sns.heatmap(df.corr(numeric_only=True), annot=True, fmt=".2f",',
            '            cmap="RdBu_r", center=0, ax=axes[1, 1])',
            'axes[1, 1].set_title("heatmap — what is redundant with what?")',
            "plt.tight_layout()",
            "plt.show()",
        ),
        md("A caution on that last panel. Correlation measures the **linear** part",
           "of a relationship only. A column can drive the target hard and still",
           "show a correlation near zero if its shape is not a line — which is",
           "exactly what happens to `hour` in the Session 2 bike challenge."),
        md("### pairplot — the first thing to run on a new table"),
        code(
            'sns.pairplot(df, hue="species", height=1.8)',
            "plt.show()",
        ),
        md("Every numeric pair at once. Read straight off it: flipper length and",
           "body mass are near-linear; Gentoo separates cleanly on almost any",
           "pair; Adelie and Chinstrap overlap everywhere except bill length —",
           "which predicts which two classes a model will confuse, before you",
           "train one.",
           "",
           "It costs $p^2$ panels, so on a wide frame restrict it:",
           "`sns.pairplot(df, vars=[\"bmi\", \"bp\"], hue=\"target\")`."),
        md("---", "", "## 5. Into a model, and back out",
           "",
           "`scikit-learn` accepts only a rectangle of numbers. One call converts",
           "every non-numeric column to indicator columns and leaves the numeric",
           "ones alone."),
        code(
            'clean = df.dropna()',
            'X = clean.drop(columns=["species"])',
            'y = (clean["species"] == "Gentoo").astype(int)',
            "",
            "X_encoded = pd.get_dummies(X)",
            'print(list(X_encoded.columns))',
        ),
        md("### The alignment trap — the part to actually read",
           "",
           "Encode train and test **separately** and they can end up with",
           "different columns: a category in one and not the other changes the",
           "width, or the order. The model is then fed nonsense, usually with no",
           "error at all.",
           "",
           "Watch it happen — a training set with no Torgersen penguins:"),
        code(
            'train = clean[clean["island"] != "Torgersen"].drop(columns=["species"])',
            'test = clean.drop(columns=["species"])',
            "",
            "a = pd.get_dummies(train)",
            "b = pd.get_dummies(test)",
            'print("train columns:", len(a.columns), list(a.columns[-3:]))',
            'print("test  columns:", len(b.columns), list(b.columns[-3:]))',
            'print("same?", list(a.columns) == list(b.columns))',
        ),
        md("Different widths. Now the fix:"),
        code(
            "b_aligned = pd.get_dummies(test).reindex(columns=a.columns, fill_value=0)",
            'print("same?", list(a.columns) == list(b_aligned.columns))',
            "assert list(a.columns) == list(b_aligned.columns)",
        ),
        md("`reindex(columns=...)` forces the second frame onto the first's exact",
           "column list — missing columns created and filled with `0`, extra",
           "columns dropped. Write the `assert` once and stop worrying about it.",
           "",
           "### Fit, predict, write"),
        code(
            "from sklearn.linear_model import LogisticRegression",
            "from sklearn.model_selection import train_test_split, cross_val_score",
            "",
            "A, B, a_y, b_y = train_test_split(X_encoded, y, test_size=0.3, random_state=0)",
            "model = LogisticRegression(max_iter=2000).fit(A, a_y)",
            'print("holdout accuracy:", round(model.score(B, b_y), 4))',
            "",
            "cv = cross_val_score(LogisticRegression(max_iter=2000), X_encoded, y, cv=5)",
            'print("5-fold CV       :", round(cv.mean(), 4))',
        ),
        md("**Accuracy 1.0 — and you should be suspicious of that.** Session 3 is",
           "entirely about why a perfect score usually means the model memorised",
           "something rather than learned it.",
           "",
           "Here it is real, and the second line is how you know: 5-fold",
           "cross-validation agrees at 0.997, so the result is not an artefact of",
           "one lucky split. Telling Gentoos apart genuinely is easy — go back to",
           "the `pairplot` and look at how far they sit from the other two on",
           "almost every pair. The measurements alone are enough; `island` on its",
           "own only reaches 0.82.",
           "",
           "That is the habit: when a score looks too good, do not celebrate and",
           "do not panic — cross-validate, and find out which column earned it."),
        code(
            'out = pd.DataFrame({"id": B.index, "prediction": model.predict(B)})',
            'out.to_csv("submission.csv", index=False)',
            "out.head()",
        ),
        md("**`index=False` is not cosmetic.** Leave it out and pandas writes its",
           "row labels as an extra unnamed leading column; the scorer sees a",
           "column it did not ask for and rejects the file.",
           "",
           "---",
           "",
           "## That is the whole surface",
           "",
           "Everything the challenge notebooks do is built from what is above. The",
           "habit worth keeping is the four lines from section 1 —",
           "`shape`, `dtypes`, `isna().sum()`, `describe()` — plus one plot of the",
           "target and one `pairplot`, on every dataset, before any modelling.",
           "",
           "It costs a minute, and it is the difference between modelling the data",
           "you have and modelling the data you assumed you had."),
    ]), name


# --------------------------------------------------------------------------- #
# 1. Bike sharing demand — the worked notebook
# --------------------------------------------------------------------------- #
def build_bike() -> dict:
    name = "aie-s2-bike-demand.ipynb"
    return notebook([
        md(
            f"# AIE S2 — Bike Sharing Demand",
            "",
            f"[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]({colab_url(name)})",
            "",
            "**Regression.** Predict how many bikes are rented in a given hour,",
            "from the calendar and the weather.",
            "",
            f"Challenge: <https://ml-arena.com/viewchallenge/{BIKE_ID}>",
            "",
            "This notebook is the worked example. It runs top to bottom and ends",
            "with a scored submission. Five steps, and every later challenge in",
            "the course is the same five:",
            "",
            "1. get the data",
            "2. look at it",
            "3. turn it into numbers",
            "4. fit a model and measure it *before* submitting",
            "5. predict the test set and submit",
        ),
        md("---", "", "## 0. Setup",
           "",
           "`pandas`, `seaborn` and `scikit-learn` are already in Colab. The",
           "ML-Arena client is what downloads the data and uploads your answer.",
           "",
           "The distribution is called **`mlarena-sdk`** and it imports as",
           "`mlarena`. Do not `pip install mlarena` — that is an unrelated",
           "package by another author, and none of the calls below exist in it."),
        code("!pip install -q mlarena-sdk"),
        md("---", "", "## 1. Get the data",
           "",
           "Paste your personal API key from your ML-Arena **Profile** page. It",
           "starts with `mlk_user_`. `download_dataset` writes the three public",
           "files into the working directory."),
        code(
            "import mlarena",
            "",
            'API_KEY = "mlk_user_..."   # <- paste yours here',
            f"CHALLENGE_ID = {BIKE_ID}",
            "",
            "client = mlarena.connect(api_key=API_KEY)",
            'client.download_dataset(CHALLENGE_ID, ".")',
        ),
        md("---", "", "## 2. Read it",
           "",
           "Three files. `X_train` and `y_train` are what you learn from;",
           "`X_test` is what you must predict. `y_test` does not exist on your",
           "side — that is the whole point of the exercise."),
        code(
            "import pandas as pd",
            "",
            'X_train = pd.read_csv("X_train.csv")',
            'y_train = pd.read_csv("y_train.csv")["prediction"]',
            'X_test = pd.read_csv("X_test.csv")',
            "",
            'print("X_train", X_train.shape, " y_train", y_train.shape, " X_test", X_test.shape)',
            "X_train.head()",
        ),
        md("`X_train` is (13903, 13): **n = 13,903 observations** and 13 columns,",
           "of which one is the `id`, so **p = 12 features**. The target lives in",
           "a separate file, aligned by `id`.",
           "",
           "Check the column types before anything else — they decide what you",
           "are allowed to do with each one."),
        code(
            "X_train.dtypes",
        ),
        md("Four columns are text (`season`, `holiday`, `workingday`, `weather`)",
           "and the rest are numbers. A linear model cannot consume the text ones",
           "as they are; step 3 is about that.",
           "",
           "Now the target and the numeric features:"),
        code(
            'print(y_train.describe().round(2))',
            "X_train.describe().round(2)",
        ),
        md("---", "", "## 3. Look at it",
           "",
           "This is the step that is easiest to skip and cheapest to do. Five",
           "plots, and each one changes a decision you are about to make.",
           "",
           "First, put the target back next to the features so seaborn can plot",
           "them together."),
        code(
            'df = X_train.assign(count=y_train)',
            'df.head(3)',
        ),
        md("### 3a. The target's distribution",
           "",
           "Always look at what you are predicting first."),
        code(
            "import matplotlib.pyplot as plt",
            "import seaborn as sns",
            "",
            'sns.set_theme(style="whitegrid")',
            "",
            "fig, ax = plt.subplots(figsize=(9, 3.5))",
            'sns.histplot(df["count"], bins=60, ax=ax, color="#2f6f9f")',
            'ax.set_title(f"Hourly rental count — mean {df[\'count\'].mean():.0f}, median {df[\'count\'].median():.0f}")',
            'ax.set_xlabel("count")',
            "plt.show()",
        ),
        md("Strongly right-skewed, and bounded below by 0. Two consequences worth",
           "holding on to: the mean sits well above the median, and a model with",
           "an unbounded output — such as a linear one — is free to predict",
           "negative rentals. It will."),
        md("### 3b. The hour of the day",
           "",
           "The single most informative plot in this dataset. Split it by",
           "`workingday`, because there is no reason a Tuesday and a Sunday should",
           "look alike."),
        code(
            "fig, ax = plt.subplots(figsize=(9, 4))",
            'sns.lineplot(data=df, x="hour", y="count", hue="workingday",',
            '             palette=["#c1553b", "#2f6f9f"], ax=ax)',
            'ax.set_title("Average rentals by hour — working days vs the rest")',
            'ax.set_xticks(range(0, 24, 2))',
            "plt.show()",
        ),
        md("Two completely different shapes. Working days have a sharp **commute",
           "double peak** at 08:00 and 17:00–18:00; non-working days have a single",
           "broad afternoon hump around 13:00–15:00.",
           "",
           "Note what this implies for the model. The relationship between `hour`",
           "and `count` is not a line — it is not even monotone. A model that",
           "multiplies `hour` by one coefficient cannot represent either curve.",
           "Remember this when you read your score."),
        md("### 3c. Temperature",
           "",
           "The obvious weather candidate."),
        code(
            "fig, axes = plt.subplots(1, 2, figsize=(11, 3.8))",
            'sns.regplot(data=df, x="temp", y="count", ax=axes[0],',
            '            scatter_kws=dict(alpha=0.08, s=6, color="#2f6f9f"),',
            '            line_kws=dict(color="#c1553b"))',
            'axes[0].set_title("Rentals vs temperature (°C)")',
            'sns.boxplot(data=df, x="weather", y="count", ax=axes[1],',
            '            order=["clear", "misty", "rain", "heavy_rain"], color="#2f6f9f")',
            'axes[1].set_title("Rentals by weather")',
            "plt.tight_layout()",
            "plt.show()",
        ),
        md("Warmer is busier, roughly linearly — this one a linear model *can*",
           "use. Weather degrades demand in the order you would guess.",
           "",
           "`heavy_rain` is worth a second look: the box is almost invisible",
           "because there are only a handful of such hours in the data. A category",
           "with three observations will not support a reliable coefficient."),
        code(
            'df["weather"].value_counts()',
        ),
        md("### 3d. What correlates with what",
           "",
           "A correlation heatmap on the numeric columns, to catch redundancy",
           "before it reaches the model."),
        code(
            'num = df.select_dtypes("number")',
            "fig, ax = plt.subplots(figsize=(7.5, 5.5))",
            'sns.heatmap(num.corr(), annot=True, fmt=".2f", cmap="RdBu_r",',
            "            center=0, ax=ax, annot_kws={\"size\": 8})",
            'ax.set_title("Correlation, numeric columns")',
            "plt.show()",
        ),
        md("`temp` and `feel_temp` correlate at **0.99** — they are the same",
           "measurement twice. Keeping both is not fatal here, but it makes the",
           "two coefficients individually meaningless: the fit can trade one",
           "against the other freely.",
           "",
           "Now look at the `hour` row: it correlates **0.39** with `count`,",
           "about the same as `temp`. Read that against plot 3b, which showed",
           "`hour` driving the target far harder than any other column. The",
           "correlation understates it badly, because correlation measures only",
           "the *linear* part of a relationship and the hour effect rises, falls,",
           "rises and falls again. A single number here cannot see a shape like",
           "that — which is why you plotted it. Section 8 puts a figure on how",
           "much this one column is really worth."),
        md("### 3e. Season and year"),
        code(
            "fig, axes = plt.subplots(1, 2, figsize=(11, 3.5))",
            'sns.barplot(data=df, x="season", y="count", ax=axes[0],',
            '            order=["spring", "summer", "fall", "winter"], color="#2f6f9f")',
            'axes[0].set_title("Rentals by season")',
            'sns.barplot(data=df, x="year", y="count", ax=axes[1], color="#2f6f9f")',
            'axes[1].set_title("Rentals by year (0 = first, 1 = second)")',
            "plt.tight_layout()",
            "plt.show()",
        ),
        md("The system grew substantially between the two years. `year` is a",
           "genuine feature here, not noise."),
        md("---", "", "## 4. Turn it into numbers",
           "",
           "`f(x)` is a function on real vectors: the text columns have to become",
           "numbers. `pd.get_dummies` one-hot encodes every non-numeric column and",
           "leaves the numeric ones alone.",
           "",
           "The `reindex` on the second line is not optional. `X_test` may not",
           "contain every category `X_train` does, so encoding the two frames",
           "independently can give them different columns. `reindex` forces the",
           "test matrix to have exactly the training columns, in the same order."),
        code(
            'X_train_enc = pd.get_dummies(X_train.drop(columns=["id"]))',
            'X_test_enc = pd.get_dummies(X_test.drop(columns=["id"])).reindex(',
            "    columns=X_train_enc.columns, fill_value=0)",
            "",
            'print("encoded:", X_train_enc.shape, "->", list(X_train_enc.columns[:6]), "...")',
            'assert list(X_train_enc.columns) == list(X_test_enc.columns)',
        ),
        md("---", "", "## 5. Fit, and measure before you submit",
           "",
           "You get one score per submission, and you should never learn anything",
           "from the leaderboard you could have learned at home. Hold out part of",
           "the training data, fit on the rest, and score yourself first."),
        code(
            "from sklearn.model_selection import train_test_split",
            "from sklearn.linear_model import LinearRegression",
            "from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error",
            "import numpy as np",
            "",
            "A_tr, A_va, b_tr, b_va = train_test_split(",
            "    X_train_enc, y_train, test_size=0.2, random_state=0)",
            "",
            "model = LinearRegression().fit(A_tr, b_tr)",
            "pred_va = model.predict(A_va)",
            "",
            'print(f"R2   {r2_score(b_va, pred_va):.4f}")',
            'print(f"RMSE {np.sqrt(mean_squared_error(b_va, pred_va)):.2f}")',
            'print(f"MAE  {mean_absolute_error(b_va, pred_va):.2f}")',
        ),
        md("Read those three numbers against the only baseline that matters —",
           "predicting the training mean for every hour, which is what **R² = 0**",
           "means:"),
        code(
            "baseline = np.full(len(b_va), b_tr.mean())",
            'print(f"predict-the-mean  R2 {r2_score(b_va, baseline):.4f}  '
            'RMSE {np.sqrt(mean_squared_error(b_va, baseline)):.2f}")',
            "",
            f'print(f"negative predictions: {{(pred_va < 0).sum()}} of {{len(pred_va)}}")',
        ),
        md("So the model does carry real signal — but it also predicts a negative",
           "number of bicycles a few hundred times, exactly as plot 3a warned.",
           "That is the linear family's unbounded output space showing up in the",
           "output."),
        md("---", "", "## 6. Predict the test set and write the submission",
           "",
           "Refit on **all** the training data now — the holdout has done its job",
           "and more data is better. Then write the two required columns."),
        code(
            "model = LinearRegression().fit(X_train_enc, y_train)",
            "predictions = model.predict(X_test_enc)",
            "",
            'submission = pd.DataFrame({"id": X_test["id"], "prediction": predictions})',
            'submission.to_csv("submission.csv", index=False)',
            "",
            'print(submission.shape)',
            "submission.head()",
        ),
        md("Check the file before uploading it. One row per test id, no missing",
           "values, no duplicates:"),
        code(
            'assert len(submission) == len(X_test)',
            'assert submission["id"].is_unique',
            'assert submission["prediction"].notna().all()',
            'print("submission.csv looks well-formed")',
        ),
        md("---", "", "## 7. Submit"),
        code(
            'result = client.submit(challenge_id=CHALLENGE_ID, files=["submission.csv"])',
            "print(result)",
        ),
        code(
            "client.leaderboard(CHALLENGE_ID).head(10)",
        ),
        md("---", "", "## 8. Where to go from here",
           "",
           "This model scores about **R² = 0.40**. The challenge page lists the",
           "ladder above it; the first rung is worth far more than you would",
           "expect, and it is not a change of model:",
           "",
           "- **`hour` is being treated as a number.** The encoding says 23:00 is",
           "  twenty-three times 1:00, and that midnight is a fall of 23 from",
           "  23:00. Plot 3b showed the real shape. Try",
           "  `X_train[\"hour\"] = X_train[\"hour\"].astype(str)` before",
           "  `get_dummies` and re-run — on this split it takes R² from 0.40 to",
           "  about 0.70, with the same `LinearRegression`.",
           "- **Predictions can be negative.** `np.clip(predictions, 0, None)` is",
           "  free and cannot hurt.",
           "- **`temp` and `feel_temp` are the same column twice.** Try dropping",
           "  one.",
           "- `month` and `weekday` have the same problem as `hour`.",
           "",
           "Everything past that — trees, ensembles, tuning — is Session 3."),
    ]), name


# --------------------------------------------------------------------------- #
# 2. Bank marketing — the guided notebook (no code)
# --------------------------------------------------------------------------- #
def build_bank() -> dict:
    name = "aie-s2-bank-marketing.ipynb"
    return notebook([
        md(
            "# AIE S2 — Bank Term Deposit",
            "",
            f"[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]({colab_url(name)})",
            "",
            "**Classification.** A Portuguese bank ran a direct marketing",
            "campaign: 45,211 calls, and for each one, whether the client",
            "subscribed a term deposit afterwards. Predict that outcome for calls",
            "you have not been shown.",
            "",
            f"Challenge: <https://ml-arena.com/viewchallenge/{BANK_ID}>",
            "",
            "---",
            "",
            "**This notebook contains no code, and that is deliberate.** You have",
            "just read the bike-demand notebook, which is the same five steps on a",
            "regression target. Here the steps are written out in English and the",
            "cells are empty. Write them yourself.",
            "",
            "Two things genuinely differ from the bike challenge, and both are",
            "flagged below where they bite: the target is a **class**, not a",
            "quantity, and it is **imbalanced** — only 11.7% of clients said yes.",
        ),
        md("---", "", "## 0. Setup",
           "",
           "Install the ML-Arena client. `pandas`, `seaborn` and `scikit-learn`",
           "are already available in Colab.",
           "",
           "The distribution is **`mlarena-sdk`** and it imports as `mlarena`.",
           "`pip install mlarena` installs an unrelated package — check you have",
           "the right one."),
        code(""),
        md("---", "", "## 1. Get the data",
           "",
           "Connect with your personal `mlk_user_...` key from your ML-Arena",
           f"Profile page, and download the dataset for challenge **{BANK_ID}**",
           "into the working directory. Same two calls as last time."),
        code(""),
        md("---", "", "## 2. Read it",
           "",
           "Load `X_train.csv`, the `prediction` column of `y_train.csv`, and",
           "`X_test.csv`.",
           "",
           "Then answer three questions before going further:",
           "",
           "- What are **n** and **p**?",
           "- Which columns are numeric and which are text?",
           "- **What fraction of the training target is 1?** Compute it now. This",
           "  number decides your metric and your reading of every result that",
           "  follows."),
        code(""),
        md("---", "", "## 3. Look at it",
           "",
           "Aim for five or six plots. For each one, ask what decision it changes",
           "— a plot that changes nothing was not worth making.",
           "",
           "**3a. The target.** Count the two classes. Confirm the imbalance you",
           "computed above, and work out what accuracy you would get by always",
           "predicting the majority class. Write that number down; it is the",
           "number your model has to be judged against.",
           "",
           "**3b. A numeric feature against the target.** Compare the",
           "distribution of `duration` (call length in seconds) for clients who",
           "subscribed and clients who did not. A boxplot or a pair of histograms",
           "will do. The separation is large — then read the note in step 4 about",
           "why that should make you uneasy rather than pleased.",
           "",
           "**3c. A categorical feature against the target.** Plot the",
           "**subscription rate** — not the raw count — per level of `poutcome`",
           "(the outcome of the previous campaign), `month`, and `job`. Raw counts",
           "will mostly tell you which levels are common; the rate is what tells",
           "you which are predictive. `groupby(col)[target].mean()` gives it to",
           "you directly.",
           "",
           "**3d. Age.** Plot the subscription rate against age in bins. It is not",
           "monotone. Note what that means for a model that multiplies age by a",
           "single coefficient.",
           "",
           "**3e. Correlation.** Heatmap the numeric columns. Check whether any",
           "pair is nearly redundant.",
           "",
           "**3f. `pdays`.** Look at its distribution. The value `-1` is a flag",
           "meaning \"never previously contacted\", not a quantity — so the column",
           "mixes a category and a measurement in one place. Decide what to do",
           "about it, and be able to say why."),
        code(""),
        code(""),
        code(""),
        md("---", "", "## 4. Turn it into numbers",
           "",
           "Same problem as before: nine of the sixteen columns are text. One-hot",
           "encode them, and align the test columns to the training ones — an",
           "encoding done independently on the two frames will not match.",
           "",
           "**Then scale the numeric columns.** This is the step the bike notebook",
           "did not need. `balance` runs from −8,019 to 102,127 while `campaign`",
           "runs from 1 to 63; the solver behind `LogisticRegression` will not",
           "converge in a sensible number of iterations if you hand it both",
           "untouched. `StandardScaler` fitted on the training matrix is enough.",
           "",
           "**A decision to make here.** `duration` is the length of the call you",
           "are predicting the outcome of. You only know it once the call has",
           "ended — so a model that relies on it could never run *before* placing",
           "the call. It is in the data and you may use it. Decide whether you",
           "want to, and say why in a comment. Both answers are defensible; an",
           "unexamined answer is not."),
        code(""),
        md("---", "", "## 5. Fit, and measure before you submit",
           "",
           "Hold out 20% of the training data, fit `LogisticRegression` on the",
           "rest, and score yourself on the holdout.",
           "",
           "Report **four** numbers: accuracy, precision, recall and F1. Then:",
           "",
           "- Compare your accuracy with the always-predict-0 accuracy from step",
           "  3a. If they are close, your accuracy is telling you nothing.",
           "- Look at precision against recall. A model that almost never predicts",
           "  1 will have decent precision and terrible recall, and F1 is the",
           "  number that refuses to let you ignore that.",
           "- A confusion matrix makes all four legible at once. Plot it.",
           "",
           "The challenge ranks on **F1 on the positive class**, for exactly the",
           "reason step 3a made visible."),
        code(""),
        code(""),
        md("---", "", "## 6. The threshold is yours",
           "",
           "`predict()` labels a client as 1 when the predicted probability",
           "exceeds 0.5. That 0.5 is a convention, not a property of the problem,",
           "and on a target that is 11.7% positive it is rarely the best choice.",
           "",
           "Use `predict_proba()` to get the probabilities, then:",
           "",
           "- Sweep the threshold from 0.05 to 0.60 and plot F1 against it on your",
           "  holdout.",
           "- Read off the best one and keep it.",
           "",
           "On this dataset the move is worth more than changing model family.",
           "Do this on the **holdout**, never on the leaderboard."),
        code(""),
        md("---", "", "## 7. Predict the test set and write the submission",
           "",
           "Refit on all the training data, predict `X_test`, and apply the",
           "threshold you chose.",
           "",
           "The submission is `submission.csv` with columns `id` and `prediction`,",
           "one row per test id. **`prediction` must be the integer 0 or 1** — a",
           "probability is rejected outright rather than thresholded for you.",
           "",
           "Assert the three things before uploading: one row per test id, ids",
           "unique, and every value in {0, 1}."),
        code(""),
        md("---", "", "## 8. Submit",
           "",
           "Submit the file and look at the leaderboard. Compare your score with",
           "the baseline quoted on the challenge page (F1 = 0.4528). If you are",
           "below it, the most likely reasons in order: you left the threshold at",
           "0.5, you did not scale, or your test columns are misaligned with your",
           "training columns."),
        code(""),
        md("---", "", "## 9. Write down what you did",
           "",
           "Two or three sentences, in the notebook:",
           "",
           "- Which metric you are reporting and why that one.",
           "- What you did about `duration`, and why.",
           "- What threshold you chose, and what it cost you in precision to buy",
           "  that recall.",
           "",
           "Being able to answer those is the point of the exercise. The score is",
           "just the receipt."),
    ]), name


# --------------------------------------------------------------------------- #
# 3. Diabetes progression — the worked notebook for Session 3
# --------------------------------------------------------------------------- #
def build_diabetes() -> dict:
    name = "aie-s3-diabetes-progression.ipynb"
    return notebook([
        md(
            "# AIE S3 — Diabetes Progression",
            "",
            f"[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]({colab_url(name)})",
            "",
            "**Regression.** Predict disease progression one year after baseline,",
            "from ten clinical measurements.",
            "",
            f"Challenge: <https://ml-arena.com/viewchallenge/{DIABETES_ID}>",
            "",
            "---",
            "",
            "This notebook exists to demonstrate one claim, on real data, with",
            "numbers you can re-run:",
            "",
            "> **Your training score is not your score.**",
            "",
            "We fit two models — a plain straight line and a 500-tree random",
            "forest — and the forest will look about twice as good. It is not.",
            "By the end you will have seen three ways to find that out, ordered",
            "from worst to best: the training score (useless), a single held-out",
            "split (better, but noisy), and cross-validation (what to actually",
            "use). Then we submit both models and let the leaderboard confirm it.",
        ),
        md("---", "", "## 0. Setup",
           "",
           "The distribution is **`mlarena-sdk`** and it imports as `mlarena`.",
           "`pip install mlarena` is an unrelated package."),
        code("!pip install -q mlarena-sdk"),
        md("---", "", "## 1. Get the data"),
        code(
            "import mlarena",
            "",
            'API_KEY = "mlk_user_..."   # <- paste yours here',
            f"CHALLENGE_ID = {DIABETES_ID}",
            "",
            "client = mlarena.connect(api_key=API_KEY)",
            'client.download_dataset(CHALLENGE_ID, ".")',
        ),
        md("---", "", "## 2. Read it"),
        code(
            "import pandas as pd",
            "",
            'X_train = pd.read_csv("X_train.csv")',
            'y_train = pd.read_csv("y_train.csv")["prediction"]',
            'X_test = pd.read_csv("X_test.csv")',
            "",
            'print("X_train", X_train.shape, " X_test", X_test.shape)',
            "X_train.head()",
        ),
        md("**n = 265 training rows, p = 10 features.** That is a small dataset,",
           "and it is small on purpose: the fewer rows you have, the easier it is",
           "for a flexible model to memorise them.",
           "",
           "The target is a continuous progression score. All ten features are",
           "numeric, so there is nothing to encode — this notebook is about",
           "validation, not preparation."),
        code(
            'print(y_train.describe().round(1))',
            "X_train.describe().round(1)",
        ),
        md("---", "", "## 3. A quick look",
           "",
           "Two plots, enough to know what we are working with."),
        code(
            "import matplotlib.pyplot as plt",
            "import seaborn as sns",
            "",
            'sns.set_theme(style="whitegrid")',
            'df = X_train.assign(target=y_train)',
            "",
            "fig, axes = plt.subplots(1, 2, figsize=(11.5, 4))",
            'sns.histplot(df["target"], bins=30, ax=axes[0], color="#2f6f9f")',
            'axes[0].set_title("Disease progression at one year")',
            "",
            'corr = df.corr(numeric_only=True)["target"].drop("target").sort_values()',
            'corr.plot.barh(ax=axes[1], color="#2f6f9f")',
            'axes[1].set_title("Correlation of each feature with the target")',
            "plt.tight_layout()",
            "plt.show()",
        ),
        md("`bmi` and `log_triglycerides` carry the most linear signal, `hdl` the",
           "most negative. Nothing here is overwhelming — this is a genuinely",
           "noisy problem, which is the second reason it was chosen."),
        md("---", "", "## 4. The trap",
           "",
           "Fit both models on the training data, and score them on **the same**",
           "training data. This is the thing you must not do, and it is worth",
           "doing once so you recognise the result when you see it in the wild."),
        code(
            "from sklearn.linear_model import LinearRegression",
            "from sklearn.ensemble import RandomForestRegressor",
            "from sklearn.metrics import r2_score",
            "",
            'X = X_train.drop(columns=["id"])',
            "",
            "linear = LinearRegression().fit(X, y_train)",
            "forest = RandomForestRegressor(n_estimators=500, random_state=0,",
            "                               n_jobs=-1).fit(X, y_train)",
            "",
            'print(f"LinearRegression   train R2 = {r2_score(y_train, linear.predict(X)):.4f}")',
            'print(f"RandomForest(500)  train R2 = {r2_score(y_train, forest.predict(X)):.4f}")',
        ),
        md("**0.51 against 0.92.** The forest explains 92% of the variance and the",
           "line barely half. On this evidence the forest is not slightly better,",
           "it is in a different league, and the obvious move is to ship it.",
           "",
           "This evidence is worthless. The forest was *shown the answers* for",
           "all 265 rows and is now being asked about those same 265 rows. It has",
           "500 trees grown until their leaves are pure — it has enough capacity",
           "to store the training set, so a high score here measures storage",
           "capacity, not skill."),
        md("---", "", "## 5. Hold some data back",
           "",
           "The cheapest honest test: fit on part of the data, score on the part",
           "the model never saw."),
        code(
            "from sklearn.model_selection import train_test_split",
            "",
            "X_fit, X_val, y_fit, y_val = train_test_split(",
            "    X, y_train, test_size=0.25, random_state=0)",
            'print(f"fit on {len(X_fit)} rows, validate on {len(X_val)}")',
            'print()',
            "",
            'for label, model in [("LinearRegression", LinearRegression()),',
            '                     ("RandomForest(500)", RandomForestRegressor(',
            "                         n_estimators=500, random_state=0, n_jobs=-1))]:",
            "    model.fit(X_fit, y_fit)",
            "    tr = r2_score(y_fit, model.predict(X_fit))",
            "    va = r2_score(y_val, model.predict(X_val))",
            '    print(f"{label:18} train {tr:.4f}   validation {va:.4f}   gap {tr - va:+.4f}")',
        ),
        md("There it is. The line loses about 0.19 between what it fitted and",
           "what it generalises; the forest loses **0.64**, and ends up *below*",
           "the line on the rows that count.",
           "",
           "That difference between the two columns is what the word",
           "**overfitting** names. It is not a property of random forests — it is",
           "what happens when a model has more capacity than the data can",
           "constrain."),
        code(
            "fig, ax = plt.subplots(figsize=(8, 4))",
            'labels = ["LinearRegression", "RandomForest(500)"]',
            "scores = {}",
            'for label, model in zip(labels, [LinearRegression(),',
            "        RandomForestRegressor(n_estimators=500, random_state=0, n_jobs=-1)]):",
            "    model.fit(X_fit, y_fit)",
            "    scores[label] = (r2_score(y_fit, model.predict(X_fit)),",
            "                     r2_score(y_val, model.predict(X_val)))",
            "",
            "import numpy as np",
            "pos = np.arange(len(labels))",
            'ax.bar(pos - 0.2, [scores[l][0] for l in labels], 0.4, label="train", color="#c1553b")',
            'ax.bar(pos + 0.2, [scores[l][1] for l in labels], 0.4, label="validation", color="#2f6f9f")',
            "ax.set_xticks(pos); ax.set_xticklabels(labels)",
            'ax.set_ylabel("R²"); ax.legend()',
            'ax.set_title("The gap between the two bars is the overfitting")',
            "plt.show()",
        ),
        md("---", "", "## 6. One split is not enough",
           "",
           "The validation set above had 67 rows. Change `random_state` and the",
           "numbers move a lot — you are estimating a score from 67 draws. Before",
           "trusting any single split, look at how much it wobbles."),
        code(
            "for seed in range(5):",
            "    A, B, a, b = train_test_split(X, y_train, test_size=0.25, random_state=seed)",
            "    lin = LinearRegression().fit(A, a)",
            "    rf = RandomForestRegressor(n_estimators=500, random_state=0, n_jobs=-1).fit(A, a)",
            '    print(f"seed {seed}:  linear {r2_score(b, lin.predict(B)):.3f}   '
            'forest {r2_score(b, rf.predict(B)):.3f}")',
        ),
        md("The individual numbers swing by more than the difference between the",
           "two models. A single split can hand you almost any conclusion,",
           "including the wrong one."),
        md("---", "", "## 7. Cross-validation",
           "",
           "Instead of holding out one block, hold out each of five in turn: fit",
           "on the other four, score on the held-out fold, repeat. Every row gets",
           "used for training four times and for scoring once, and you end up",
           "with five estimates instead of one.",
           "",
           "`cross_val_score` does the whole loop."),
        code(
            "from sklearn.model_selection import cross_val_score",
            "import numpy as np",
            "",
            'for label, model in [("LinearRegression", LinearRegression()),',
            '                     ("RandomForest(500)", RandomForestRegressor(',
            "                         n_estimators=500, random_state=0, n_jobs=-1))]:",
            '    cv = cross_val_score(model, X, y_train, cv=5, scoring="r2")',
            '    print(f"{label:18} CV R2 = {cv.mean():.4f} +/- {cv.std():.4f}   '
            'folds {np.round(cv, 3)}")',
        ),
        md("Two things to read here.",
           "",
           "**The mean settles the argument.** 0.427 for the line against 0.358",
           "for the forest — the line generalises better, and we established that",
           "without touching a single test label.",
           "",
           "**The spread explains section 6.** The individual folds run from about",
           "0.27 to 0.63 for the line alone. That range *is* the noise a single",
           "split was sampling from. Reporting one number from one split is",
           "reporting one draw from that distribution and calling it the answer.",
           "",
           "This is the number to make decisions on."),
        md("---", "", "## 8. The forest is not the problem — its settings are",
           "",
           "An unrestricted tree grows until every leaf is pure. Force the leaves",
           "to hold at least `min_samples_leaf` rows and the model can no longer",
           "memorise individuals. Watch both curves as we turn that dial."),
        code(
            "leaves = [1, 2, 5, 10, 20, 40]",
            "train_scores, cv_scores = [], []",
            "for leaf in leaves:",
            "    rf = RandomForestRegressor(n_estimators=500, min_samples_leaf=leaf,",
            "                               random_state=0, n_jobs=-1)",
            "    train_scores.append(r2_score(y_train, rf.fit(X, y_train).predict(X)))",
            '    cv_scores.append(cross_val_score(rf, X, y_train, cv=5, scoring="r2").mean())',
            "",
            "fig, ax = plt.subplots(figsize=(8.5, 4.5))",
            'ax.plot(leaves, train_scores, "o-", color="#c1553b", label="train R²")',
            'ax.plot(leaves, cv_scores, "o-", color="#2f6f9f", label="5-fold CV R²")',
            'ax.axhline(0.4273, ls="--", c="gray", lw=1, label="LinearRegression CV")',
            'ax.set_xscale("log"); ax.set_xticks(leaves)',
            "ax.set_xticklabels(leaves)",
            'ax.set_xlabel("min_samples_leaf  (less flexible ->)")',
            'ax.set_ylabel("R²"); ax.legend()',
            'ax.set_title("Constraining the forest costs training score and buys generalisation")',
            "plt.show()",
            "",
            "for leaf, tr, cv in zip(leaves, train_scores, cv_scores):",
            '    print(f"min_samples_leaf={leaf:<3} train {tr:.4f}   CV {cv:.4f}   gap {tr - cv:+.4f}")',
        ),
        md("The red curve falls the whole way — every constraint costs training",
           "score. The blue curve *rises* to a peak around `min_samples_leaf=10`",
           "and then falls again: too little capacity is its own failure.",
           "",
           "This is the bias–variance tradeoff, drawn from your own data. The",
           "gap between the curves shrinks from 0.56 to 0.09. And note where the",
           "blue curve peaks relative to the dashed line — even tuned, the forest",
           "does not overtake the straight line on this dataset. Sometimes the",
           "simple model is simply right."),
        md("---", "", "## 9. Predict the test set and submit both",
           "",
           "Refit both on all 265 rows and write two submissions. We submit the",
           "forest as well as the line, on purpose: the leaderboard is an",
           "independent referee and you should watch it agree with the CV."),
        code(
            "linear = LinearRegression().fit(X, y_train)",
            "forest = RandomForestRegressor(n_estimators=500, random_state=0, n_jobs=-1).fit(X, y_train)",
            "",
            'X_test_features = X_test.drop(columns=["id"])',
            'for fname, model in [("submission.csv", linear), ("forest.csv", forest)]:',
            '    pd.DataFrame({"id": X_test["id"],',
            '                  "prediction": model.predict(X_test_features)}).to_csv(fname, index=False)',
            '    print(f"wrote {fname}")',
        ),
        code(
            'assert len(pd.read_csv("submission.csv")) == len(X_test)',
            'result = client.submit(challenge_id=CHALLENGE_ID, files=["submission.csv"],',
            '                       agent_name="linear-regression")',
            "print(result)",
        ),
        md("Now the forest. `submit` uploads each file under its basename and the",
           "challenge expects `submission.csv`, so copy it to that name first."),
        code(
            "import shutil",
            'shutil.copy("forest.csv", "submission.csv")',
            'result = client.submit(challenge_id=CHALLENGE_ID, files=["submission.csv"],',
            '                       agent_name="random-forest-500")',
            "print(result)",
        ),
        md("Scoring takes a moment. Then look at the board:"),
        code(
            "client.leaderboard(CHALLENGE_ID)",
        ),
        md("---", "", "## 10. What to take away",
           "",
           "The challenge page lists the full ladder. Two facts from it are worth",
           "carrying out of this session:",
           "",
           "- Of six models tried on this split, **the two with the best training",
           "  score have the worst test score**, and the straight line — last on",
           "  training — is first on test.",
           "- Rank those six by 5-fold CV on the training set alone and you",
           "  recover the test ranking **exactly**, without ever seeing a test",
           "  label.",
           "",
           "So the working rule for the rest of the course:",
           "",
           "> Choose models on cross-validation. Use the held-out set once, to",
           "> confirm.",
           "",
           "And the corollary people forget: **the leaderboard is a test set too.**",
           "Submit twenty variants and keep the best, and you have fitted 177 rows",
           "by hand — the same mistake, one level up. Your CV score is the",
           "estimate you should believe."),
    ]), name


# --------------------------------------------------------------------------- #
# 4. Credit risk — the guided notebook for Session 3
# --------------------------------------------------------------------------- #
def build_credit() -> dict:
    name = "aie-s3-credit-risk.ipynb"
    return notebook([
        md(
            "# AIE S3 — Credit Risk",
            "",
            f"[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]({colab_url(name)})",
            "",
            "**Classification.** 1,000 loan applications with 20 attributes each;",
            "predict which applicants are **bad credit risks**.",
            "",
            f"Challenge: <https://ml-arena.com/viewchallenge/{CREDIT_ID}>",
            "",
            "---",
            "",
            "**No code here, on purpose.** You have just worked through the",
            "diabetes notebook, which ran the whole protocol on a continuous",
            "target. This is the same protocol on a class label, and you write",
            "it.",
            "",
            "The dataset has been chosen so the Session 3 lesson repeats in an",
            "even blunter form. You are going to fit a random forest that gets",
            "**every single training applicant right** — and loses anyway.",
        ),
        md("---", "", "## 0. Setup",
           "",
           "Install the ML-Arena client. The distribution is **`mlarena-sdk`**",
           "and it imports as `mlarena`; `pip install mlarena` is a different",
           "package."),
        code(""),
        md("---", "", "## 1. Get the data",
           "",
           "Connect with your `mlk_user_...` key and download the dataset for",
           f"challenge **{CREDIT_ID}** into the working directory."),
        code(""),
        md("---", "", "## 2. Read it",
           "",
           "Load the three files. Then answer, before modelling:",
           "",
           "- What are **n** and **p**?",
           "- How many columns are text rather than numeric?",
           "- **What fraction of the training target is 1?** Compute it, and work",
           "  out the accuracy you would get by predicting 0 for everybody. Write",
           "  that number down — it is the floor every result must clear."),
        code(""),
        md("---", "", "## 3. A quick look",
           "",
           "Three or four plots, no more. This challenge is about validation, not",
           "exploration.",
           "",
           "- The class balance.",
           "- The **bad-risk rate** per level of `checking_status` and of",
           "  `credit_history` — the rate, not the raw count. `groupby` then",
           "  `.mean()` on the target gives it directly.",
           "- `duration` and `credit_amount` split by the target. Do longer, larger",
           "  loans go bad more often?"),
        code(""),
        code(""),
        md("---", "", "## 4. Turn it into numbers",
           "",
           "Thirteen of the twenty columns are categorical. One-hot encode them",
           "and align the test columns to the training ones, or the two matrices",
           "will not have the same shape.",
           "",
           "Scale the numeric columns as well — `credit_amount` runs to five",
           "figures while `installment_commitment` is single digits, and the",
           "logistic solver will not converge nicely on that mix."),
        code(""),
        md("---", "", "## 5. Walk into the trap first",
           "",
           "Fit two models on **all** the training data and score them on **that",
           "same data**:",
           "",
           "- `LogisticRegression`",
           "- `RandomForestClassifier(n_estimators=500)` — unrestricted",
           "",
           "Report training accuracy for both. One of them will be **1.0000**.",
           "",
           "Stop and say out loud what that number means before you continue. It",
           "does not mean the model is perfect. It means the model has enough",
           "capacity to store 700 answers, and you have just measured its",
           "memory."),
        code(""),
        md("---", "", "## 6. Now measure honestly",
           "",
           "Two things, in this order.",
           "",
           "**A held-out split.** Carve 25% off the training data, refit both",
           "models on the rest, and report accuracy **and F1** on the part they",
           "did not see. Put the training and validation numbers side by side and",
           "look at the gap for each model.",
           "",
           "**Then cross-validation.** Run 5-fold CV on the full training set for",
           "both models, scoring `f1`. Report the mean and the standard",
           "deviation.",
           "",
           "Compare the two exercises. The single split gives you one number; CV",
           "gives you five and their spread. If the gap between your two models",
           "is smaller than the spread across folds, you have not actually",
           "separated them — say so rather than picking the higher mean."),
        code(""),
        code(""),
        md("---", "", "## 7. Fix the forest",
           "",
           "The forest is not a bad model; it is an unconstrained one. Sweep",
           "`min_samples_leaf` over something like `[1, 2, 5, 10, 20, 40]` and for",
           "each value record **training F1** and **5-fold CV F1**.",
           "",
           "Plot both against the parameter, on one pair of axes.",
           "",
           "You should get two curves: one that falls the whole way, and one that",
           "rises to a peak and then falls. Name which is which, and say which",
           "value you would choose and why. That plot is the bias–variance",
           "tradeoff drawn from your own data."),
        code(""),
        md("---", "", "## 8. Choose the threshold",
           "",
           "`predict()` cuts at probability 0.5. With 30% positives that is",
           "usually the wrong place.",
           "",
           "Take `predict_proba()` from your best model, sweep the threshold from",
           "0.15 to 0.60, and plot F1 against it — **on your validation split or",
           "your CV folds, never on the leaderboard**. Keep the best.",
           "",
           "Then state the tradeoff in words: at your chosen threshold, what",
           "happened to precision, and what did you buy with it? In a credit",
           "setting, which of the two errors is more expensive?"),
        code(""),
        md("---", "", "## 9. Submit",
           "",
           "Refit your chosen model on all 700 training rows, predict `X_test`,",
           "apply your threshold, and write `submission.csv` with columns `id`",
           "and `prediction`, where `prediction` is the integer 0 or 1. A",
           "probability is rejected, not rounded for you.",
           "",
           "Assert before uploading: one row per test id, ids unique, all values",
           "in {0, 1}. Then submit and compare against the benchmark on the",
           "challenge page (F1 = 0.5714).",
           "",
           "Submit the unrestricted forest too, if you want to watch the",
           "leaderboard agree with your cross-validation."),
        code(""),
        code(""),
        md("---", "", "## 10. Write down what you found",
           "",
           "Four sentences in the notebook:",
           "",
           "- What training accuracy the unrestricted forest reached, and what it",
           "  actually scored held out.",
           "- Which model your cross-validation chose, and whether the leaderboard",
           "  agreed.",
           "- Which `min_samples_leaf` you picked and what the two curves looked",
           "  like.",
           "- What threshold you used, and which error you decided was worse.",
           "",
           "If your CV ranking and your leaderboard ranking disagree, that is a",
           "result worth reporting, not a mistake to hide — with 300 test rows,",
           "differences smaller than your fold-to-fold spread are noise."),
    ]), name


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    global _COUNTER
    for builder in (build_preflight, build_bike, build_bank,
                    build_diabetes, build_credit):
        _COUNTER = itertools.count()
        nb, name = builder()
        path = OUT / name
        path.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n")
        n_code = sum(1 for c in nb["cells"] if c["cell_type"] == "code")
        n_md = sum(1 for c in nb["cells"] if c["cell_type"] == "markdown")
        print(f"  wrote {path.relative_to(REPO)}  ({n_md} md + {n_code} code cells)")
        print(f"        {colab_url(name)}")


if __name__ == "__main__":
    main()
