name: Enforce and Evaluate

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-and-evaluate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetches all history for branches and tags

    - name: Fetch base and head branches
      run: |
        git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
        git fetch origin ${{ github.head_ref }}:refs/remotes/origin/${{ github.head_ref }}

    - name: Check folder permissions and determine changed TPs
      id: check-and-determine
      run: |
        # Extract GitHub username from actor
        USER="${{ github.actor }}"

        # Get list of changed files compared to the base branch
        FILES_CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }})

        # Check if changes are only within user's folder
        echo "Checking folder permissions..."
        for FILE in $FILES_CHANGED; do
          if [[ "$FILE" != "$USER/"* && "$FILE" != "common/"* ]]; then
            echo "::error file=$FILE,Title=Unauthorized File Modification::You can only modify files in your own directory."
            exit 1
          fi
        done

        # Determine the unique TP numbers that have changes
        echo "Determining changed TPs..."
        CHANGED_TPS=$(echo "$FILES_CHANGED" | grep "^${USER}/TP" | sed -E 's|.*/TP([0-9]+)/.*|\1|' | sort | uniq)
        echo "changed_tps=$CHANGED_TPS" >> $GITHUB_ENV

    - name: Run Tests
      run: |
        # Source the changed TPs from the environment
        CHANGED_TPS=${{ env.changed_tps }}
        USER="${{ github.actor }}"

        # Convert the space-separated list to an array
        IFS=' ' read -r -a TPS_ARRAY <<< "$CHANGED_TPS"

        # Run tests for each changed TP
        for TP in "${TPS_ARRAY[@]}"; do
          ./tests/run_tests.sh "$USER" "tp$TP"
        done
