name: Enforce and Evaluate

on:
  push:
    branches:
      - main

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: main
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    # Log the event name and event path for debugging purposes
    - name: Log Event Name and Path
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "Event Path: $GITHUB_EVENT_PATH"