name: Enforce and Evaluate

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-and-evaluate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetches all history for branches and tags

    - name: Fetch base and head branches
      run: |
        git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
        git fetch origin ${{ github.head_ref }}:refs/remotes/origin/${{ github.head_ref }}

    - name: Check folder permissions and determine changed MODULES
      id: check-and-determine
      run: |
        USER="${{ github.actor }}"
        FILES_CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }})
        echo "FILES_CHANGED: $FILES_CHANGED"

        echo "Checking folder permissions..."
        for FILE in $FILES_CHANGED; do
          if [[ "$FILE" != "$USER/"* && "$FILE" != "common/"* ]]; then
            echo "::error file=$FILE,Title=Unauthorized File Modification::You can only modify files in your own directory."
            exit 1
          fi
        done